---
- name: Copy helper scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - slapd-attribute-upsert
    - slapd-create-monitor
    - slapd-create-overlay
    - slapd-olc-attribute-clean
    - slapd-global-modules
    - slapd-global-schema
    - slapd-mdb-create
    - slapd-overlay-attribute-upsert
    - slapd-overlay-dn
    - slapd-overlay-olc-attribute-clean
    - slapd-password-hash

# Global
- import_tasks: global-schemas.yml
- import_tasks: global-config.yml
- import_tasks: global-modules.yml
# Frontend
- import_tasks: frontend-config.yml
# OLC
- import_tasks: olc-config.yml
# MDB
- import_tasks: mdb-create.yml
- include_tasks: mdb-overlay-create.yml
  with_dict: "{{ slapd_mdb_overlays }}"
  when: "slapd_mdb_overlays is not undefined"
- include_tasks: mdb-overlay-config.yml
  with_dict: "{{ slapd_mdb_overlays }}"
  when: "slapd_mdb_overlays is not undefined"
- import_tasks: mdb-config.yml
# Monitor
- import_tasks: monitor-create.yml
  when: slapd_enable_monitor
- import_tasks: monitor-config.yml
  when: slapd_enable_monitor
